// Command stackql-mcp-fetch downloads the signed stackql MCP release
// bundle for one or more platforms, verifies each against its published
// sha256 pin, extracts the server binary, and writes the go:embed glue
// that exposes it as an embed.Binary.
//
// Intended use is a go:generate directive in the package that embeds the
// binary:
//
//	//go:generate go run github.com/stackql/stackql-mcp-go/cmd/stackql-mcp-fetch -platform all -package main
//
// then, on the consuming side:
//
//	client, err := stackqlmcp.StartServer(ctx, stackqlmcp.Options{Binary: StackqlMCPBinary()})
//
// The binary files (stackql-mcp-<platform-key>) belong in .gitignore;
// regenerate them in CI before building.
package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stackql/stackql-mcp-go/embed"
	"github.com/stackql/stackql-mcp-go/internal/fetch"
)

var buildTags = map[string]string{
	embed.PlatformLinuxX64:        "linux && amd64",
	embed.PlatformLinuxARM64:      "linux && arm64",
	embed.PlatformWindowsX64:      "windows && amd64",
	embed.PlatformDarwinUniversal: "darwin",
}

func main() {
	version := flag.String("version", embed.DefaultVersion, "stackql release version (no leading v)")
	platform := flag.String("platform", "auto", "platform key, 'auto' for the current platform, or 'all'")
	dir := flag.String("dir", ".", "output directory")
	pkg := flag.String("package", "", "if set, write <dir>/stackql_mcp_<platform>_gen.go with go:embed glue for this package name")
	flag.Parse()

	var platforms []string
	switch *platform {
	case "all":
		platforms = []string{
			embed.PlatformLinuxX64,
			embed.PlatformLinuxARM64,
			embed.PlatformWindowsX64,
			embed.PlatformDarwinUniversal,
		}
	case "auto":
		key, err := embed.CurrentPlatformKey()
		if err != nil {
			fatal(err)
		}
		platforms = []string{key}
	default:
		if _, ok := buildTags[*platform]; !ok {
			fatal(fmt.Errorf("unknown platform key %q", *platform))
		}
		platforms = []string{*platform}
	}

	client := &http.Client{Timeout: 10 * time.Minute}
	for _, key := range platforms {
		if err := fetchOne(client, *version, key, *dir, *pkg); err != nil {
			fatal(fmt.Errorf("%s: %w", key, err))
		}
	}
}

func fetchOne(client *http.Client, version, key, dir, pkg string) error {
	fmt.Fprintf(os.Stderr, "fetching stackql-mcp-%s.mcpb v%s\n", key, version)
	res, err := fetch.Bundle(client, version, key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	binPath := filepath.Join(dir, "stackql-mcp-"+key)
	if err := os.WriteFile(binPath, res.Binary.Data, 0o755); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s (binary sha256 %s, bundle pin %s)\n", binPath, res.Binary.SHA256, res.BundleSHA)
	if pkg == "" {
		return nil
	}
	genPath := filepath.Join(dir, "stackql_mcp_"+strings.ReplaceAll(key, "-", "_")+"_gen.go")
	src := fmt.Sprintf(`// Code generated by stackql-mcp-fetch. DO NOT EDIT.
// stackql v%[1]s %[2]s, extracted from the pin-verified release bundle
// (bundle sha256 %[5]s).

//go:build %[3]s

package %[4]s

import (
	_ "embed"

	stackqlmcpembed "github.com/stackql/stackql-mcp-go/embed"
)

//go:embed stackql-mcp-%[2]s
var stackqlMCPData []byte

// StackqlMCPBinary returns the embedded stackql server binary for %[2]s.
func StackqlMCPBinary() stackqlmcpembed.Binary {
	return stackqlmcpembed.Binary{
		Data:        stackqlMCPData,
		Version:     %[1]q,
		PlatformKey: %[2]q,
		SHA256:      %[6]q,
	}
}
`, version, key, buildTags[key], pkg, res.BundleSHA, res.Binary.SHA256)
	if err := os.WriteFile(genPath, []byte(src), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", genPath)
	return nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "stackql-mcp-fetch:", err)
	os.Exit(1)
}
