package testobjects

//nolint:lll,revive,stylecheck // This is a test file
const (
	ExpectedSelectOktaApplicationAppsJSON                                     string = "test/assets/expected/okta/select-apps.csv"
	ExpectedSimpleSelectGoogleComputeInstanceTableFile01                      string = "test/assets/expected/simple-select/google/compute/instances/table/simple-select-variant-01.txt"
	ExpectedSimpleSelectGoogleComputeInstanceTableFile02                      string = "test/assets/expected/simple-select/google/compute/instances/table/simple-select-variant-02.txt"
	ExpectedSimpleSelectGoogleComputeInstanceTextFile01                       string = "test/assets/expected/simple-select/google/compute/instances/text/simple-select-variant-01.csv"
	ExpectedSimpleSelectGoogleComputeInstanceTextFile02                       string = "test/assets/expected/simple-select/google/compute/instances/text/simple-select-variant-02.csv"
	ExpectedSimpleSelectGoogleCotainerSubnetworkTableFile01                   string = "test/assets/expected/simple-select/google/container/agg-subnetworks-allowed/table/simple-select-variant-01.txt"
	ExpectedSimpleSelectGoogleCotainerSubnetworkTableFile02                   string = "test/assets/expected/simple-select/google/container/agg-subnetworks-allowed/table/simple-select-variant-02.txt"
	ExpectedSimpleSelectGoogleCotainerSubnetworkTextFile01                    string = "test/assets/expected/simple-select/google/container/agg-subnetworks-allowed/text/simple-select-variant-01.csv"
	ExpectedSimpleSelectGoogleCotainerSubnetworkTextFile02                    string = "test/assets/expected/simple-select/google/container/agg-subnetworks-allowed/text/simple-select-variant-02.csv"
	ExpectedK8STheHardWayRenderedFile                                         string = "test/assets/expected/k8s-the-hard-way/k8s-the-hard-way.iql"
	ExpectedShowInsertAddressesRequiredFile                                   string = "test/assets/expected/simple-templating/insert-compute-addresses-required.iql"
	ExpectedShowInsertBQDatasetsFile                                          string = "test/assets/expected/simple-templating/insert-bigquery-datasets.iql"
	ExpectedShowInsertBQDatasetsRequiredFile                                  string = "test/assets/expected/simple-templating/insert-bigquery-datasets-required.iql"
	ExpectedComputeNetworkInsertAsyncFile                                     string = "test/assets/expected/simple-insert/compute-network/insert-compute-network.txt"
	ExpectedComputeDisksDependentInsertAsyncFile                              string = "test/assets/expected/simple-insert/compute-disk/insert-dependent-compute-disk.txt"
	ExpectedBQDatasetsDependentInsertFile                                     string = "test/assets/expected/simple-insert/bq-datasets/insert-dependent-bq-datasets.txt"
	ExpectedComputeNetworkDeleteAsyncFile                                     string = "test/assets/expected/simple-delete/compute-network/delete-compute-network.txt"
	ExpectedK8STheHardWayAsyncFile                                            string = "test/assets/expected/k8s-the-hard-way/k8s-the-hard-way-e2e/success.txt"
	ExpectedShowResourcesFilteredFile                                         string = "test/assets/expected/show/show-resources-filtered.csv"
	ExpectedShowMethodsGoogleBQDatasetsFile                                   string = "test/assets/expected/show/show-methods-google-bigquery-datasets.csv"
	ExpectedShowMethodsGoogleStorageBucketsFile                               string = "test/assets/expected/show/show-methods-google-storage-buckets.csv"
	ExpectedSimpleAggCountGroupedGoogleCotainerSubnetworkTableFileAsc         string = "test/assets/expected/aggregated-select/google/container/agg-subnetworks-allowed/table/simple-count-grouped-variant-asc.txt"
	ExpectedSimpleAggCountGroupedGoogleCotainerSubnetworkTableFileDesc        string = "test/assets/expected/aggregated-select/google/container/agg-subnetworks-allowed/table/simple-count-grouped-variant-desc.txt"
	ExpectedSimpleAggCountGroupedGoogleCotainerSubnetworkTextFileAsc          string = "test/assets/expected/aggregated-select/google/container/agg-subnetworks-allowed/text/simple-count-grouped-variant-asc.csv"
	ExpectedSimpleAggCountGroupedGoogleCotainerSubnetworkTextFileDesc         string = "test/assets/expected/aggregated-select/google/container/agg-subnetworks-allowed/text/simple-count-grouped-variant-desc.csv"
	ExpectedSelectComputeDisksOrderCrtTmstpAsc                                string = "test/assets/expected/simple-select/google/compute/disks/text/disks-order-crt-tmstp-asc.csv"
	ExpectedSelectComputeDisksOrderCrtTmstpAscPlusJsonExtract                 string = "test/assets/expected/function-select/google/compute/disks/text/disks-order-crt-tmstp-asc-json-extract.csv"
	ExpectedSelectComputeDisksOrderCrtTmstpAscPlusJsonExtractCoalesce         string = "test/assets/expected/function-select/google/compute/disks/text/disks-order-crt-tmstp-asc-json-extract-coalesce.csv"
	ExpectedUnionAllSelectComputeDisksOrderCrtTmstpAscPlusJsonExtractCoalesce string = "test/assets/expected/function-select/google/compute/disks/text/union-all-disks-order-crt-tmstp-asc-json-extract-coalesce.csv"
	ExpectedSelectComputeDisksOrderCrtTmstpAscPlusJsonExtractInstr            string = "test/assets/expected/function-select/google/compute/disks/text/disks-order-crt-tmstp-asc-json-extract-instr.csv"
	ExpectedSelectComputeDisksAggSizeOrderSizeAsc                             string = "test/assets/expected/aggregated-select/google/disks/text/disks-grp-by-sizeGb-order-crt-tmstp-asc.csv"
	ExpectedSelectComputeDisksAggSizeOrderSizeDesc                            string = "test/assets/expected/aggregated-select/google/disks/text/disks-grp-by-sizeGb-order-crt-tmstp-desc.csv"
	ExpectedSelectComputeDisksAggSizeTotal                                    string = "test/assets/expected/aggregated-select/google/disks/text/disks-sizeGb-total-sum.csv"
	ExpectedSelectComputeDisksAggStringTotal                                  string = "test/assets/expected/aggregated-select/google/disks/text/disks-total-string-agg.csv"
	ExpectedSelectComputeDisksOrderCrtTmstpAscPaginated                       string = "test/assets/expected/simple-select/google/compute/disks-paginated/text/disks-order-crt-tmstp-asc.csv"
	ExpectedSelectComputeDisksAggPaginatedSizeOrderSizeAsc                    string = "test/assets/expected/aggregated-select/google/disks-paginated/text/disks-grp-by-sizeGb-order-crt-tmstp-asc.csv"
	ExpectedSelectComputeDisksAggPaginatedSizeOrderSizeDesc                   string = "test/assets/expected/aggregated-select/google/disks-paginated/text/disks-grp-by-sizeGb-order-crt-tmstp-desc.csv"
	ExpectedSelectComputeDisksAggPaginatedSizeTotal                           string = "test/assets/expected/aggregated-select/google/disks-paginated/text/disks-sizeGb-total-sum.csv"
	ExpectedSelectComputeDisksAggPaginatedStringTotal                         string = "test/assets/expected/aggregated-select/google/disks-paginated/text/disks-total-string-agg.csv"
	ExpectedSelectExecOrgGetIamPolicyAgg                                      string = "test/assets/expected/aggregated-select/google/cloudresourcemanager/select-exec-getiampolicy-agg.csv"
	ExpectedSelectComputeDisksWindowRowNumber                                  string = "test/assets/expected/window-select/google/disks/text/disks-window-row-number.csv"
	ExpectedSelectComputeDisksWindowRank                                       string = "test/assets/expected/window-select/google/disks/text/disks-window-rank.csv"
	ExpectedSelectComputeDisksWindowSum                                        string = "test/assets/expected/window-select/google/disks/text/disks-window-sum.csv"
	ExpectedSelectComputeDisksWindowDenseRank                                  string = "test/assets/expected/window-select/google/disks/text/disks-window-dense-rank.csv"
	ExpectedSelectComputeDisksWindowMultiple                                   string = "test/assets/expected/window-select/google/disks/text/disks-window-multiple.csv"
	ExpectedSelectComputeDisksWindowCount                                      string = "test/assets/expected/window-select/google/disks/text/disks-window-count.csv"
	ExpectedSelectComputeDisksCTEWithWindow                                    string = "test/assets/expected/window-select/google/disks/text/disks-cte-with-window.csv"
	ExpectedSelectComputeDisksCTESimple                                        string = "test/assets/expected/cte-select/google/disks/text/disks-cte-simple.csv"
	ExpectedSelectComputeDisksCTEWithAgg                                       string = "test/assets/expected/cte-select/google/disks/text/disks-cte-with-agg.csv"
	ExpectedSelectComputeDisksCTEMultiple                                      string = "test/assets/expected/cte-select/google/disks/text/disks-cte-multiple.csv"
)
