// Package contributors credits the humans behind stackql: the vendored
// leaderboard behind SHOW CONTRIBUTORS (issue #320). contributors.csv is
// regenerated by the contributors workflow and compiled in, so the build
// stays hermetic and each release freezes its credits.
package contributors

import (
	_ "embed"
	"encoding/csv"
	"strconv"
	"strings"
	"sync"
)

//go:embed contributors.csv
var contributorsCSV string //nolint:gochecknoglobals // embed target

// csvFields is the column count of contributors.csv: contributor,contributions.
const csvFields = 2

// Contributor is one leaderboard entry.
type Contributor interface {
	GetLogin() string
	GetContributions() int
}

type contributor struct {
	login         string
	contributions int
}

func (c contributor) GetLogin() string      { return c.login }
func (c contributor) GetContributions() int { return c.contributions }

//nolint:gochecknoglobals // parsed once
var (
	parseOnce sync.Once
	parsed    []Contributor
)

// List returns the leaderboard in vendored order (contributions descending).
func List() []Contributor {
	parseOnce.Do(func() { parsed = parse(contributorsCSV) })
	return parsed
}

// parse skips the header and any malformed line.
func parse(raw string) []Contributor {
	records, err := csv.NewReader(strings.NewReader(raw)).ReadAll()
	if err != nil || len(records) == 0 {
		return nil
	}
	rv := make([]Contributor, 0, len(records)-1)
	for _, rec := range records[1:] {
		if len(rec) != csvFields {
			continue
		}
		n, convErr := strconv.Atoi(strings.TrimSpace(rec[1]))
		if convErr != nil || strings.TrimSpace(rec[0]) == "" {
			continue
		}
		rv = append(rv, contributor{login: strings.TrimSpace(rec[0]), contributions: n})
	}
	return rv
}
