name: goreleaser

# run only on new tags
on:
  push:
    tags:
      - 'release*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      

      - name: Get rid of dissruptive line endings before checkout
        run: |
          git config --global core.autocrlf false
          
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}